# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.Usuario')),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'ALUNO',
            },
            bases=('authentication.usuario',),
        ),
        migrations.CreateModel(
            name='ArquivoQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'ARQUIVO_QUESTAO',
            },
        ),
        migrations.CreateModel(
            name='ArquivoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'ARQUIVO_RESPOSTA',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.Usuario')),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'COORDENADOR',
            },
            bases=('authentication.usuario',),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CURSO',
            },
        ),
        migrations.CreateModel(
            name='CursoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
            ],
            options={
                'db_table': 'CURSO_TURMA',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, unique=True)),
                ('carga_horaria', models.IntegerField()),
                ('teoria', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pratica', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ementa', models.TextField()),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('conteudo', models.TextField()),
                ('bibliografia_basica', models.TextField(blank=True, null=True)),
                ('bibliografia_complementar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DISCIPLINA',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('id_disciplina', models.ForeignKey(db_column='id_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
            ],
            options={
                'db_table': 'DISCIPLINA_OFERTADA',
            },
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
            ],
            options={
                'db_table': 'GRADE_CURRICULAR',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno')),
                ('id_disciplina', models.ForeignKey(db_column='id_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.DisciplinaOfertada')),
            ],
            options={
                'db_table': 'MATRICULA',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('id_grade', models.ForeignKey(db_column='id_grade', on_delete=django.db.models.deletion.DO_NOTHING, to='core.GradeCurricular')),
            ],
            options={
                'db_table': 'PERIODO',
            },
        ),
        migrations.CreateModel(
            name='PeriodoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disciplina', models.ForeignKey(db_column='id_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Periodo')),
            ],
            options={
                'db_table': 'PERIODO_DISCIPLINA',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.Usuario')),
                ('apelido', models.CharField(max_length=30, unique=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'PROFESSOR',
            },
            bases=('authentication.usuario',),
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('data_limite_entrega', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('id_disciplina', models.ForeignKey(db_column='id_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.DisciplinaOfertada')),
            ],
            options={
                'db_table': 'QUESTAO',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avaliacao', models.TextField()),
                ('descricao', models.TextField()),
                ('data_de_envio', models.DateField()),
                ('id_aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno')),
                ('id_questao', models.ForeignKey(db_column='id_questao', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questao')),
            ],
            options={
                'db_table': 'RESPOSTA',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.CharField(max_length=1)),
                ('turno', models.CharField(max_length=15)),
                ('id_disciplina', models.ForeignKey(db_column='id_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
                ('id_professor', models.ForeignKey(db_column='id_professor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Professor')),
            ],
            options={
                'db_table': 'TURMA',
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set([('sigla', 'nome')]),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='id_resposta',
            field=models.ForeignKey(db_column='id_resposta', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Resposta'),
        ),
        migrations.AddField(
            model_name='arquivoquestao',
            name='id_questao',
            field=models.ForeignKey(db_column='id_questao', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questao'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_curso',
            field=models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set([('id_disciplina', 'id_turma', 'turno')]),
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together=set([('id_aluno', 'id_questao')]),
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together=set([('id_turma', 'numero')]),
        ),
        migrations.AlterUniqueTogether(
            name='periododisciplina',
            unique_together=set([('id_periodo', 'id_disciplina')]),
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together=set([('id_grade', 'numero')]),
        ),
        migrations.AlterUniqueTogether(
            name='gradecurricular',
            unique_together=set([('id_curso', 'ano', 'semestre')]),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together=set([('id_disciplina', 'ano', 'semestre')]),
        ),
        migrations.AlterUniqueTogether(
            name='cursoturma',
            unique_together=set([('id_curso', 'id_turma')]),
        ),
    ]
